sudo:          false
language:      node_js
addons:
  apt:
    packages:
    - lftp
node_js:
  - 10
install:
  - npm install
script:
  - gulp
cache:
  directories:
    - node_modules

after_success:
  - lftp sftp://admiral.instruktori.cz:8022
    -u civilizace.instruktori.cz,$PASSWORD
    -e 'mirror --reverse --verbose --delete --exclude=.git --exclude=node_modules . /public_html; exit'

