sudo:          false
language:      node_js
node_js:
  - 10
install:
  - npm install
script:
  - gulp
cache:
  directories:
    - node_modules

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master